name : Site Web

on:
  push:
    branches:
      - master

jobs:

  deploy-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Upload files on FTP server
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
            # Adresse du serveur
            server: sftp.exemple.com
            # Numéro de port
            port: 22
            # Nom d'utilisateur
            username: ${{ secrets.username }}
            # Mot de passe
            password: ${{ secrets.password }}
            # Dossier de destination dans le serveur (absolu, ou relatif...)
            remote_path: /public/www/ftpinfo.iutmontp.univ-montp2.fr
            # Si on utilise sftp
            sftp_only: true